name: CI
on:
- push
jobs:
  function-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
      working-directory: ./func-dojo-cicd-skool
    - run: npm test
      working-directory: ./func-dojo-cicd-skool
  test-coverage:
    runs-on: ubuntu-latest
    needs:
    - function-tests
    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p ./reports/jest
    - run: npm install
      working-directory: ./func-dojo-cicd-skool
    - run: npx jest --coverage --coverage-directory=../reports/jest
      working-directory: ./func-dojo-cicd-skool
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: jest-reports
        path: ./reports/jest
  eslint:
    runs-on: ubuntu-latest
    needs:
    - function-tests
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p ./reports/eslint
    - run: npm install
      working-directory: ./func-dojo-cicd-skool
    - run: npx eslint ./DojoCicdSkool
      working-directory: ./func-dojo-cicd-skool
  build:
    runs-on: ubuntu-latest
    needs:
    - eslint
    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p ./reports/eslint
    - run: npm install
      working-directory: ./func-dojo-cicd-skool
    - run: npm run build
      working-directory: ./func-dojo-cicd-skool
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./func-dojo-cicd-skool/dist
